src/vsx2_tools_web/app/views/base.py
from flask import request, render_template, Blueprint, redirect, make_response, url_for

base = Blueprint("base", __name__, url_prefix="")


@base.route("/")
@base.route("/index")
def index():
    return render_template("index.html")


@base.route("/setlang", methods=["get"])
def setlang():
    referrer = request.referrer or url_for("base.index")
    resp = make_response(redirect(referrer, code=302))
    resp.set_cookie("locale", request.values.get("locale"))
    return resp

src/vsx2_tools_web/app/views/layout.py
from flask_babel import _

from flask import request, render_template, json, Blueprint, Response

from vsx2_change_layout import change_layout
from ..models.forms import LayoutForm


layout = Blueprint("layout", __name__, url_prefix="/layout")


@layout.route("/", methods=["get", "post"])
def index():
    form = LayoutForm()
    if form.validate_on_submit():
        result_str = change_layout(
            source_str=form.input_.data,
            source_layout=form.source.data,
            destination_layout=form.destination.data,
        )
        return Response(
            response=json.dumps(
                {
                    "result": result_str,
                }
            ),
            status=200,
            mimetype="application/json",
        )
    if request.method == "POST":
        return Response(
            response=json.dumps(
                {
                    "errors": form.errors,
                }
            ),
            status=400,
            mimetype="application/json",
        )
    return render_template("layout.html", page_title=_("layoutPageTitle"), form=form)

src/vsx2_tools_web/app/views/meme_generator.py
import os
from io import BytesIO
import platform
from typing import Tuple, Optional

from PIL import Image, ImageDraw, ImageFont, ImageColor
from flask import Blueprint, render_template, request, abort, send_file
from flask_babel import _
from pyclamd import ClamdUnixSocket, ConnectionError as ClamdConnectionError

from ..models.forms import MemeGeneratorForm

meme_generator = Blueprint("meme_generator", __name__, url_prefix="/meme_generator")


class MemeGeneratorValidationError(Exception):
    def __init__(self, *args, status_code=400):
        super().__init__(*args)
        self.status_code = status_code


class MemeGenerator:
    def __init__(self, file, text: str, text_color: str):
        self.__image: Image = Image.open(file)

        self.__image_width, self.__image_height = self.__image.size

        self.__text: str = text
        self.__draw: ImageDraw.Draw = ImageDraw.Draw(self.__image)

        self.__max_font_size_cached: Optional[int] = None
        self.__load_font()
        self.__load_text_size()
        self.__text_color = text_color  # ImageColor.getcolor(text_color, "RGB")

    def __load_font(self):
        current_file_path = os.path.dirname(os.path.abspath(__file__))
        path_to_font = os.path.join(
            current_file_path, "..", "static", "fonts", "Lobster-Regular.ttf"
        )
        self.__font: ImageFont = ImageFont.truetype(path_to_font, self.__font_size)

    def __load_text_size(self):
        self.__text_width, self.__text_height = self.__draw.textsize(
            self.__text, self.__font
        )

    @property
    def __font_size(self) -> int:
        calculated_size = int(self.__image_width / len(self.__text))
        if calculated_size > self.__max_font_size:
            return self.__max_font_size
        return calculated_size

    @property
    def __max_font_size(self) -> int:
        if self.__max_font_size_cached:
            return self.__max_font_size_cached

        size = int(self.__image_height / 10)
        if size < 5:
            raise MemeGeneratorValidationError(
                "invalid image size:( we cannot use this image as template"
            )

        self.__max_font_size_cached = size

        return size

    @property
    def __text_position(self) -> Tuple[int, int]:
        x = int((self.__image_width - self.__text_width + 1) / 2)
        y = int(self.__image_height - self.__font_size * 1.5)
        return x, y

    def __call__(self) -> Tuple[BytesIO, str, str]:
        self.__draw.text(
            self.__text_position, self.__text, self.__text_color, font=self.__font
        )

        img_io: BytesIO = BytesIO()
        self.__image.save(img_io, self.__image.format, quality=100)
        img_io.seek(0)

        return img_io, self.__image.get_format_mimetype(), self.__image.format.lower()


@meme_generator.route("/", methods=["get", "post"])
def index():
    if request.values.get("secret") != "hb.png112233":
        return abort(404)
    error = None
    form = MemeGeneratorForm()
    if form.validate_on_submit():
        try:
            f = form.image.data
            if platform.system() == "Linux":
                socket = ClamdUnixSocket()
                try:
                    result = socket.scan_stream(f)
                except ClamdConnectionError:
                    raise MemeGeneratorValidationError(
                        "Something went wrong :( Please contact me at me@vldsx.com",
                        status_code=500,
                    )
                finally:
                    socket._close_socket()
                if result:
                    raise MemeGeneratorValidationError("Virus detected in file :(")
            file, mimetype, file_type = MemeGenerator(
                f, form.text.data, form.text_color.data
            )()
            kwargs = {"mimetype": mimetype}
            if request.values.get("download") == "Download":
                kwargs.update(
                    {
                        "as_attachment": True,
                        "download_name": f"meme_from_vldsx.{file_type}",
                    }
                )
            return send_file(file, **kwargs)
        except MemeGeneratorValidationError as e:
            error = e

    status = 400 if form.errors else 200
    return (
        render_template(
            "meme_generator.html",
            page_title=_("memeGeneratorPageTitle"),
            error_message=str(error) if error else "",
            meme_text=request.values.get("text") or "",
            form=form,
            text_color=request.values.get("text_color") or "#ffffff",
        ),
        error.status_code if error and error.status_code else status,
    )

src/vsx2_tools_web/app/views/role_formatter.py
from flask_babel import _

from flask import render_template, Blueprint

role_formatter = Blueprint("role_formatter", __name__, url_prefix="/role_formatter")


@role_formatter.route("/", methods=["get"])
def index():
    return render_template(
        "role_formatter.html", page_title=_("roleFormatterPageTitle")
    )

src/vsx2_tools_web/app/views/rotate.py
from flask_babel import _

from flask import request, render_template, json, Blueprint, Response

from vsx2_rotate import get_rotated_string, ROTATE_MAP
from ..models.forms import RotateForm

rotator = Blueprint("rotator", __name__, url_prefix="/rotate")


@rotator.route("/", methods=["get", "post"])
def index():
    form = RotateForm()
    if form.validate_on_submit():
        result_str = get_rotated_string(form.input_.data)
        return Response(
            response=json.dumps(
                {
                    "result": result_str,
                }
            ),
            status=200,
            mimetype="application/json",
        )
    if request.method == "POST":
        return Response(
            response=json.dumps(
                {
                    "errors": form.errors,
                }
            ),
            status=400,
            mimetype="application/json",
        )

    return render_template("rotate.html", page_title=_("rotatePageTitle"), form=form)


@rotator.route("/doc", methods=["get"])
def doc():
    return render_template(
        "rotate_doc.html", page_title=_("rotateDocPageTitle"), mapping=ROTATE_MAP
    )

src/vsx2_tools_web/app/views/strikethrough.py
import json

from flask_babel import _

from flask import render_template, Blueprint, Response

from ..models.forms import StrikethroughForm

strikethrough = Blueprint("strikethrough", __name__, url_prefix="/strikethrough")


@strikethrough.route("/", methods=["get", "post"])
def index():
    form = StrikethroughForm(meta={"csrf": False})
    if form.validate_on_submit():
        result_str = ""
        for i in form.input_.data:
            result_str += i + "\u0336"
        return Response(
            response=json.dumps(
                {
                    "result": result_str,
                }
            ),
            status=200,
            mimetype="application/json",
        )
    # TODO: return response with validation error
    return render_template(
        "strikethrough.html", page_title=_("strikethroughPageTitle"), form=form
    )

src/vsx2_tools_web/app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>VLDSX {{ _('utilsLabel') }} {{ page_title }}</title>
        {% assets "css_all" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}">
        {% endassets %}
    </head>
    <body class="bg-light">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="https://vldsx.com"><img src="{{ url_for('static', filename='logo/logo-dark.png') }}" alt="VLDSX"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="https://vldsx.com">{{ _('mainPage') }}</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('base.index') }}">{{ _('utilsLabel') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://cities.vldsx.com">OWM Cities</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a
                            class="nav-link dropdown-toggle"
                            href="#"
                            id="language-selector"
                            data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                        >
                            {{ locale|upper }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="language-selector">
                            {% for lang in config.LANGUAGES %}
                                {% if lang != locale|lower %}
                                    <a class="dropdown-item" href="{{ url_for('base.setlang', locale=lang) }}">{{ lang.upper() }}</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container-fluit">
            {% block content %}{% endblock %}
        </div>

        {% assets "js_all" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}
        {% block additional_js %}{% endblock %}
    </body>
    <footer class="text-center text-lg-start">
        <div class="text-center p-3">
            VLDSX {{ _('utilsLabel') }} v{{ app_version }}({{ build_number }})
        </div>
    </footer>
</html>

src/vsx2_tools_web/app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <ul>
        <li>
            <a href="{{ url_for('layout.index') }}">
                {{ _('layoutPageTitle') }}
            </a>
        </li>
        <li>
            <a href="{{ url_for('strikethrough.index') }}">
                {{ _('strikethroughPageTitle') }}
            </a>
        </li>
        <li>
            <a href="{{ url_for('rotator.index') }}">
                {{ _('rotatePageTitle') }}
            </a>
        </li>
        <li>
            <a href="{{ url_for('role_formatter.index') }}">
                {{ _('roleFormatterPageTitle') }}
            </a>
        </li>
    </ul>
{% endblock %}

src/vsx2_tools_web/app/templates/layout.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ _('layoutPageTitle') }}</h1>
    <div class="main-content">
        {% if request.method == 'GET' and (request.values.get('i') or request.values.get('source') or request.values.get('destination')) %}
            <div class="alert alert-warning" role="alert">
                {{ _('deprecationWarning') }}
            </div>
        {% endif %}
        <form
            class="js-form"
            action="{{ url_for('layout.index') }}"
        >
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="input_">{{ _("inputAreaLabel") }}</label>
                {{ form.input_(class="form-control inputarea", rows="3") }}
            </div>
            <div class="row form-container justify-content-center align-items-center">
                <div class="form-group col-lg-2">
                    {{ form.source(class="form-control") }}
                </div>
                <div class="form-group col-lg-1 text-center">
                    <span class="d-lg-block d-none">
                        &rarr;
                    </span>
                    <span class="d-lg-none">
                        &darr;
                    </span>
                </div>
                <div class="form-group col-lg-2">
                    {{ form.destination(class="form-control") }}
                </div>
            </div>
            <div class="row submit-container">
                <input type="submit" class="col-12 btn btn-dark submit" value="{{ _('layoutActionButton') }}"/>
            </div>
            <div class="form-group">
                <label for="outputarea">
                    {{ _('layoutOutputAreaLabel') }}
                </label>
                <textarea
                    class="form-control outputarea"
                    rows="3"
                    id="outputarea"
                    id="outputarea"
                    disabled="disabled"
                ></textarea>
            </div>
            <button
                class="btn btn-dark copy"
                title="{{ _('copyButtonTitle') }}"
                data-success="{{ _('successCopiedMessage') }}"
            >
                ⎘ {{ _('copyButtonLabel') }}
            </button>
        </form>
    </div>
{% endblock %}

{% block additional_js %}
    {% if request.method == 'GET' and (request.values.get('i') or request.values.get('source') or request.values.get('destination')) %}
        <script>
            $(document).ready(() => {
                setTimeout(() => {
                    const $input = $('#input_');
                    $input.val("{{ request.values.get('i') }}");
                    $('#source').val("{{ request.values.get('source') }}");
                    $('#destination').val("{{ request.values.get('destination') }}");
                    $('form').submit();
                }, 100);
            });
        </script>
    {% endif %}
{% endblock %}

src/vsx2_tools_web/app/templates/meme_generator.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ _('memeGeneratorPageTitle') }} (BETA)</h1>
    <div class="main-content">
        {% if error_message %}
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
        {% endif %}
        <form method="post" enctype='multipart/form-data'>
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="text">{{ _("inputAreaLabel") }}</label>
                {{ form.text(class="form-control") }}
            </div>
            {% if form.text.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ '\n'.join(form.text.errors) }}
                </div>
            {% endif %}
            <div class="form-group">
                <label for="image">{{ _("uploadImageFieldLabel") }} {{ _("sizeLimitLabel") }}</label>
                {{ form.image(accept="image/png, image/jpeg", class="form-control") }}
            </div>
            {% if form.image.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ '\n'.join(form.image.errors) }}
                </div>
            {% endif %}
            <div class="form-group">
                <label for="text_color">{{ _("colorFieldLabel") }}</label>
                {{ form.text_color() }}
            </div>
            {% if form.text_color.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ '\n'.join(form.text_color.errors) }}
                </div>
            {% endif %}
            <div class="row">
                <div class="col">
                    <input type="submit" class="col-12 btn btn-dark submit" value="{{ _('generateButtonLabel') }}"/>
                </div>
                <div class="col">
                    <input type="submit" class="col-12 btn btn-dark submit" name="download" value="{{ _('downloadButtonLabel') }}"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

src/vsx2_tools_web/app/templates/role_formatter.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ _('roleFormatterPageTitle') }}</h1>
    <div id="app-formatter" class="main-content">
        <div class="form-group">
            <label for="inputarea">{{ _('inputAreaLabel') }}</label>
            <input
                v-model="input"
                id="inputarea"
                class="form-control inputarea"
            />
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-custom col-lg-4 col-md-6">
                    <label for="length_select">
                        {{ _('roleLengthFieldLabel') }}
                    </label>
                    <select id="length_select" v-model="roleLength" class="form-control">
                        <option
                            v-for="option in roleLengthOptions"
                            v-bind:value="option[0]"
                        >
                            [[ option[1] ]]
                        </option>
                    </select>
                </div>
                <div class="col-custom col-lg-2 col-md-6">
                    <label for="invert">
                        {{ _('invertSpacesSidesFieldLabel') }}
                    </label>
                    <div>
                        <div class="custom-control custom-switch space-side-inverter">
                            <input type="checkbox" id="invert" v-model="invertDirection" class="custom-control-input"/>
                            <label class="custom-control-label" for="invert">
                                <span v-if="invertDirection">{{ _('rightFirstLabel') }}</span>
                                <span v-else>{{ _('leftFirstLabel') }}</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-custom col-lg-2 col-md-6">
                    <label for="custom_border">{{ _('borderSymbolFieldLabel') }}</label>
                    <input
                        v-model="customBorder"
                        id="custom_border"
                        class="form-control inputarea"
                    />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="outputarea">
                {{ _('formattedRoleLabel') }}
            </label>
            <input
                class="form-control"
                ref="output"
                disabled="disabled"
                v-model="output"
                id="outputarea"
            />
        </div>
        <button
            class="btn btn-dark copy"
            title="{{ _('copyButtonTitle') }}"
            @click="copyResult"
            data-success="{{ _('successCopiedMessage') }}"
        >
            ⎘ {{ _('copyButtonLabel') }}
        </button>
{#        <h3>#}
{#            {{ _('joinOurDiscordServerLabel') }}:#}
{#        </h3>#}
    </div>


{% endblock %}

{% block additional_js %}
    {% assets "js_vue" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}

src/vsx2_tools_web/app/templates/rotate.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ _('rotatePageTitle') }}</h1>
    <div class="main-content">
        {% if request.method == 'GET' and request.values.get('i') %}
            <div class="alert alert-warning" role="alert">
                {{ _('deprecationWarning') }}
            </div>
        {% endif %}
        <form
            class="js-form"
            action="{{ url_for('rotator.index') }}"
        >
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="input_">{{ _("inputAreaLabel") }}</label>
                {{ form.input_(class="form-control inputarea", rows="3") }}
            </div>
            <div class="row submit-container">
                <input type="submit" class="col-12 btn btn-dark submit" value="{{ _('rotateActionButton') }}"/>
            </div>
            <div class="form-group">
                <label for="outputarea">
                    {{ _('rotateOutputAreaLabel') }}
                </label>
                <textarea
                    class="form-control outputarea"
                    rows="3"
                    id="outputarea"
                    disabled="disabled"
                ></textarea>
            </div>
            <button
                class="btn btn-dark copy"
                title="{{ _('copyButtonTitle') }}"
                data-success="{{ _('successCopiedMessage') }}"
            >
                ⎘ {{ _('copyButtonLabel') }}
            </button>
            <button
                class="btn btn-dark share"
                title="{{ _('shareButtonTitle') }}"
                data-success="{{ _('successCopiedMessage') }}"
            >
                {{ _('shareButtonLabel') }}
            </button>
        </form>
        <p>
            {{ _('docLinkLabel') }}
            <a href="{{ url_for('rotator.doc') }}" target="_blank">
                {{ _('docLinkLabel2') }}
            </a>
        </p>
    </div>
{% endblock %}

{% block additional_js %}
    {% if request.method == 'GET' and request.values.get('i') %}
        <script>
            $(document).ready(() => {
                setTimeout(() => {
                    const $input = $('#input_');
                    $input.val("{{ request.values.get('i') }}");
                    $input.submit();
                }, 100);
            });
        </script>
    {% endif %}
{% endblock %}

src/vsx2_tools_web/app/templates/rotate_doc.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ _('docPageTitle') }}</h1>
    <div class="main-content">
        <p>
            {{ _('rotateTextLabel') }}
            <a href="{{ url_for('rotator.index') }}" target="_blank">
                {{ _('rotateTextLabel2') }}
            </a>
        </p>
        <table class="table table-striped table-bordered">
            <colgroup>
                <col style="width: 50%"/>
                <col style="width: 50%"/>
            </colgroup>
            <thead>
                <tr>
                    <th>{{ _('symbolLabel') }}</th>
                    <th>{{ _('rotatedSymbolLabel') }}</th>
                </tr>
            </thead>
            <tbody>
                {% for key, val in mapping.items() %}
                    <tr>
                        <td>
                            {{ key }}
                        </td>
                        <td>
                            {{ val }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/vsx2_tools_web/app/templates/strikethrough.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ _('strikethroughPageTitle') }}</h1>
    <div class="main-content">
        {% if request.method == 'GET' and request.values.get('i') %}
            <div class="alert alert-warning" role="alert">
                {{ _('deprecationWarning') }}
            </div>
        {% endif %}
        <form
            class="js-form"
            action="{{ url_for('strikethrough.index') }}"
            data-type="add-symbol"
        >
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="input_">{{ _("inputAreaLabel") }}</label>
                {{ form.input_(class="form-control inputarea", rows="3") }}
            </div>
            <div class="form-group">
                <label for="outputarea">
                    {{ _('strikethroughOutputAreaLabel') }}
                </label>
                <textarea
                    class="form-control outputarea"
                    rows="3"
                    id="outputarea"
                    disabled="disabled"
                ></textarea>
            </div>
            <button
                class="btn btn-dark copy"
                title="{{ _('copyButtonTitle') }}"
                data-success="{{ _('successCopiedMessage') }}"
            >
                ⎘ {{ _('copyButtonLabel') }}
            </button>
        </form>
    </div>
{% endblock %}

{% block additional_js %}
    {% if request.method == 'GET' and request.values.get('i') %}
        <script>
            $(document).ready(() => {
                setTimeout(() => {
                    const $input = $('#input_');
                    $input.val("{{ request.values.get('i') }}");
                    $input.keyup();
                }, 100);
            });
        </script>
    {% endif %}
{% endblock %}